### ISSUE TITLE
Can't crawl an IP block

### ISSUE THREAD

**Issue by BRVT** [ninoseki/shodanx#12]
`api.scan.crawl(ips)`

I'm trying to crawl through an IP block such as 1.2.3.4/24 and it's giving an error in the request block

> base.rb:43:in `block in request': Empty list of IPs

I already tried to put the literal format and a json format such as it's indicated in the Shodan website:

```
{
    "ips": {
        "{ips}": [
            {service},
            {service},
            ...
        ],
        ...
    }
}

```
Maybe i'm doing it the worng way, can you help ?

**Comment by ninoseki** [comment]
Excuse me, I'm not sure what you mean.

```ruby
require "shodan"

api = Shodan::API.new
p api.scan.crawl("1.1.1.1/32")
```

It works without any error.

**Comment by BRVT** [comment]
I copied and paste your code and has given me this error
The only thing I changed was that I gave the key directly to the new instance of the API

![image](https://user-images.githubusercontent.com/48284903/106889161-8c266a00-66df-11eb-9581-c92fc46cd909.png)

Probably I'm doing something wrong but I don't know what

**Comment by ninoseki** [comment]
Please share your script.(Of course, please mask your API key)
Also, please do not post a log as an image. It's difficult to read it.

**Comment by BRVT** [comment]
Literally what you wrote
![image](https://user-images.githubusercontent.com/48284903/106894127-6d77a180-66e6-11eb-881d-b93c13fab2e1.png)

**Comment by ninoseki** [comment]
Do not share the code/log as an image.

**Comment by BRVT** [comment]
> Do not share the code/log as an image.

Sorry, edited.

**Comment by ninoseki** [comment]
It does not happen in my env (Ruby v2.7.2). Thus, Sorry, I cannot help you.
